name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      # This flag is the secret to fixing the ERESOLVE error
      run: npm install --legacy-peer-deps

    - name: Run ESLint
      # We tell it to use your specific config file
      run: npx eslint . --config eslint.config.mjs
